######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 3 17:42:09 2014
######################################################################

TEMPLATE = lib
CONFIG += plugin

TARGET = ../../core/eblplugin
# Directories

INCLUDEPATH += ../../

HEADERS += eblplugin.h ../../emslogviewplugin.h

SOURCES += eblplugin.cpp
