######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 3 17:42:09 2014
######################################################################

TEMPLATE = lib
CONFIG += plugin

TARGET = ../../core/megasquirtplugin
# Directories

INCLUDEPATH += ../../

HEADERS += megasquirtplugin.h ../../emslogviewplugin.h

SOURCES += megasquirtplugin.cpp
